export const C = {
  card: {
    background: 'var(--card-bg,rgba(38,40,50,1))',
    borderRadius: 12,
    border: '1px solid rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  title: {
    fontSize: 11,
    fontWeight: 500,
    color: '#d0d0e0',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    flexShrink: 0,
    display: 'inline-block',
  },
  badge: {
    fontSize: 10,
    padding: '1px 6px',
    borderRadius: 4,
    fontWeight: 500,
  },
  chev: {
    color: '#dcdcec',
    fontSize: 16,
    lineHeight: 1,
    display: 'inline-block',
    flexShrink: 0,
    transition: 'transform 0.2s',
  },
  inp: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.09)',
    borderRadius: 8,
    padding: '7px 10px',
    color: '#e4e4f4',
    fontSize: 12,
    outline: 'none',
    fontFamily: "'DM Sans',sans-serif",
  },
  btn: {
    background: 'color-mix(in srgb, var(--accent) 15%, transparent)',
    border: '1px solid color-mix(in srgb, var(--accent) 30%, transparent)',
    borderRadius: 8,
    color: 'var(--accent)',
    fontSize: 12,
    padding: '7px 14px',
    cursor: 'pointer',
    fontWeight: 500,
    fontFamily: "'DM Sans',sans-serif",
  },
  skel: width => ({
    height: 10,
    borderRadius: 4,
    background: 'rgba(255,255,255,0.05)',
    width: `${width}%`,
    animation: 'pulse 1.5s ease infinite',
    marginBottom: 8,
  }),
};
